#define CHARACTER_HEAL_POINT 100
#define CHARACTER_BOMB_RANGE 3
#define CHARACTER_NUMBER_BOMB 1
#define CHARACTER_MOVEMENT_SPEED 10
#define CHARACTER_TIME_TO_BOMB_EXPLODE 3000

#define BOMB_IS_NOT_PLACED 0
#define BOMB_IS_PLACED_ON_GROUND 1
#define BOMB_IS_EXPLODING 2
#define BOMB_HAS_EXPLODED 3
#define BOMB_TIME_BLAST_EXPLOSION 1000

#define WALL_INDESTRUCTIBLE 48
#define WALL_SQUISHY 49
#define WALL_STRONG 57

#define TILE_FREE 1
#define TILE_WITH_WALL 2
#define TILE_WITH_BOMB 3
#define TILE_WITH_CHARACTER 4

#define PATH_LEVEL = "./level/"
