#define TEXT_MENU_MONOPLAYER 0
#define TEXT_MENU_MULTIPLAYER 1
#define TEXT_MENU_QUIT 2
#define TEXT_MENU_SELECTOR_LEFT 3
#define TEXT_MENU_SELECTOR_RIGHT 4
#define TEXT_MENU_MAP_WIDTH_STR 5
#define TEXT_MENU_MAP_HEIGHT_STR 6
#define TEXT_MENU_TILE_DESTRUCTIBLE_STR 7
#define TEXT_MENU_TILE_EMPTY_STR 8
#define TEXT_MENU_NUMBER_PLAYERS 9
#define TEXT_MENU_BACK 10
// #define TEXT_MENU_TILE_DESTRUCTIBLE_VALUE 9
// #define TEXT_MENU_TILE_EMPTY_VALUE 10
// #define TEXT_MENU_MAP_WIDTH_VALUE 11
// #define TEXT_MENU_MAP_HEIGHT_VALUE 12

#define TEXT_TERRAIN_0 0
#define TEXT_TERRAIN_1 1
#define TEXT_TERRAIN_2 2
#define TEXT_TERRAIN_3 3
#define TEXT_TERRAIN_4 4
#define TEXT_TERRAIN_5 5
#define TEXT_TERRAIN_6 6
#define TEXT_TERRAIN_7 7
#define TEXT_TERRAIN_8 8
#define TEXT_TERRAIN_9 9
#define TEXT_TERRAIN_EMPTY 10
#define TEXT_TERRAIN_OUTSIDE_0 11
#define TEXT_TERRAIN_OUTSIDE_1 12
#define TEXT_TERRAIN_OUTSIDE_2 13

#define TEXT_CHARACTER_0 0
#define TEXT_CHARACTER_1 1
#define TEXT_CHARACTER_2 2
#define TEXT_CHARACTER_3 3
#define TEXT_CHARACTER_4 4
#define TEXT_CHARACTER_5 5
#define TEXT_CHARACTER_6 6
#define TEXT_CHARACTER_7 7
#define TEXT_CHARACTER_8 8
#define TEXT_CHARACTER_9 9
#define TEXT_CHARACTER_10 10
#define TEXT_CHARACTER_11 11
#define TEXT_CHARACTER_12 12
#define TEXT_CHARACTER_13 13
#define TEXT_CHARACTER_14 14
#define TEXT_CHARACTER_15 15

#define TEXT_BOMB_PLANTED 0
#define TEXT_BOMB_UNSTABLE 1
#define TEXT_BOMB_EXP_0 2
#define TEXT_BOMB_EXP_1 3

#define TEXT_MISC_LIFE_GAUGE 0
