#define TEXT_MENU_MONOPLAYER 0
#define TEXT_MENU_MULTIPLAYER 1
#define TEXT_MENU_QUIT 2
#define TEXT_MENU_SELECTOR_LEFT 3
#define TEXT_MENU_SELECTOR_RIGHT 4
#define TEXT_MENU_TILE_DESTRUCTIBLE_STR 5
#define TEXT_MENU_TILE_EMPTY_STR 6
#define TEXT_MENU_MAP_WIDTH_STR 7
#define TEXT_MENU_MAP_HEIGHT_STR 8
#define TEXT_MENU_TILE_DESTRUCTIBLE_VALUE 9
#define TEXT_MENU_TILE_EMPTY_VALUE 10
#define TEXT_MENU_MAP_WIDTH_VALUE 11
#define TEXT_MENU_MAP_HEIGHT_VALUE 12

#define TEXT_GAME_WALL_0 0
#define TEXT_GAME_WALL_1 1
#define TEXT_GAME_WALL_9 9
#define TEXT_GAME_WALL_EMPTY 10
